### ISSUE TITLE
.obj produced by aobaker are not parsed correctly

### ISSUE THREAD

**Issue by bkaradzic** [joeld42/tk_objfile#1]
If you get aobaker form here:

```
https://github.com/prideout/aobaker
```

Run:

```
aobaker --outmesh x.obj --atlas x.png suzanne.obj
```

Then run:

```
objviewer x.obj
```

Object looks like:

![screen shot 2016-01-03 at 12 18 06](https://cloud.githubusercontent.com/assets/814772/12080583/1cb9b120-b214-11e5-9354-b51d8c2317ba.png)

**Comment by joeld42** [comment]
Thanks for filing this! Should be fixed now, and baked suzanne seems to load fine. Added this mesh to the test objs.
![screen shot 2016-01-05 at 11 36 12 pm](https://cloud.githubusercontent.com/assets/24752/12137395/0ecd2b62-b405-11e5-9e68-4641066d7870.png)
